name: deploy-book 

# Only run this when the master branch changes
on:
  [push]
    #- master
    # If your git repository has the Jupyter Book within some-subfolder next to
    # unrelated files, you can make this run only if a file within that specific
    # folder has been modified.
    #
    # paths:
    # - some-subfolder/**

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r book/requirements.txt

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build .

    # Push the book's HTML to github-pages
    #- name: GitHub Pages action
    #  if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'

    #  uses: peaceiris/actions-gh-pages@v3.8.0
    #  with:
    #    #deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
    #    #github_token: ${{ secrets.GITHUB_TOKEN }}
    #    #ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        
    #    publish_dir: ./_build/html
        
        
    - name: Deploy      
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_branch: your-branch
        publish_dir: ./public
  

